<a href="https://colab.research.google.com/github/wojtek2kdev/Obliczenia_naukowe/blob/main/30.03.2022/lekcja.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

A = np.random.randint(10, size=(5,5))
%timeit eig_val, eig_vec = np.linalg.eig(A)
np.max(eig_val)

The slowest run took 7.29 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 35.6 µs per loop


(22.446219845395106+0j)

In [16]:
import numpy as np 
from numpy.linalg import inv, eigvals

A = np.array([[1,0],[0,2]])
B = np.array([[3,1],[1,2]])

C = B @ A @ inv(B)
eigvals(C)


array([1., 2.])

In [26]:
import numpy as np

A = np.random.randint(10, size=(5,5))
O1, D, O2 = np.linalg.svd(A)
B = O1 @ np.diag(D) @ O2

In [27]:
import numpy as np

A = np.random.randint(10, size=(5,5))
np.linalg.qr(A)

(array([[-0.70064905,  0.52656816,  0.1344216 ,  0.4512845 ,  0.10044907],
        [-0.38924947, -0.14133852,  0.09395842, -0.61524516,  0.66419386],
        [-0.23354968, -0.80069914,  0.03493443,  0.52293663,  0.17219841],
        [-0.54494926, -0.24126156, -0.11504059, -0.37424151, -0.70109352],
        [-0.07784989,  0.05850757, -0.97910566,  0.06554591,  0.16604846]]),
 array([[-12.84523258,  -6.9286406 ,  -5.91659198,  -6.69509092,
         -11.67748416],
        [  0.        ,  -9.21921577,  -0.97687925,   2.10298568,
          -4.56556286],
        [  0.        ,   0.        ,  -4.69464017,  -7.33650304,
          -5.84689908],
        [  0.        ,   0.        ,   0.        ,   2.63228645,
           2.47834057],
        [  0.        ,   0.        ,   0.        ,   0.        ,
           8.85796809]]))

In [52]:
import numpy as np

A = np.array([[1,2,3,1,2,1,0,1,0]]).reshape(3,3)
O1, D, O2 = np.linalg.svd(A)
eig_val, eig_vec = np.linalg.eig(A)

B = A[:2]
SVD = np.linalg.svd(B)
C = SVD[0] @ np.concatenate((np.diag(SVD[1]), np.zeros((2,1))), axis=1) @ SVD[2]
C

array([[1., 2., 3.],
       [1., 2., 1.]])

In [64]:
import numpy as np

A = np.array([[1,2,3,1,2,1,0,1,0]]).reshape(3,3)
J, P = np.linalg.eig(A)

B = P @ np.diag(J)**20 @ np.linalg.inv(P)


array([[1.69689090e+10-1.64637822e-06j, 4.16871511e+10+3.29275644e-06j,
        2.67869523e+10+7.78525577e-20j],
       [1.45358507e+10-1.41031507e-06j, 3.57099096e+10+2.82063013e-06j,
        2.29461505e+10-8.64595148e-21j],
       [4.20514992e+09-4.07997195e-07j, 1.03307007e+10+8.15994389e-07j,
        6.63820820e+09+4.10216869e-20j]])

In [66]:
import numpy as np

A = np.array([[1,2,3,1,2,1,0,1,0]]).reshape(3,3)
np.linalg.cond(A)

11.87432495287239

In [72]:
import numpy as np

A = np.array([[1,0,2,3,2,1,1,1,1]]).reshape(3,3)

b1 = np.array([[20.001, -9.9999, 100.00001]]).reshape(-1,1)

b2 = np.array([[20,-10,100]]).reshape(-1,1)

print(np.linalg.cond(A), np.linalg.solve(A, b1), np.linalg.solve(A, b2), sep="\n\n")

10.617346008950063

[[-133.33294667]
 [ 156.66598333]
 [  76.66697333]]

[[-133.33333333]
 [ 156.66666667]
 [  76.66666667]]
