# Laboratorium 

#### Zadanie 1
Napisz metodę, która oblicza pole między osią OX a wykresem funkcji na danym przedziale za pomocą sum Riemanna (przybliżeń prostokątami). Sprawdź jej działanie na wybranej przez siebie funkcji porównując z wynikiem całkownia symbolicznego. 

Korzystając z symbolicznych pochodnych i szukania ekstremów dobierz takie parametry do swojej funkcji, aby błąd całkowania był mniejszy niż $10^{-5}$.


In [ ]:
import numpy as np

from sympy import symbols, diff, solve, integrate
from functools import partial
from math import ceil

def integration(f,a,b,N):
  P = np.linspace(a,b,N)[:-1]
  dx = (b-a)/(N-1)
  return sum(dx*f(x_k) for x_k in P)

def area(f,a,b,bias):
  N = estimate_n(f,a,b,bias)
  return integration(lambda x: abs(f(x)),a,b,N)

def abs_sup(f,a,b):
  potential_points = solve(diff(f))
  return max(map(abs, map(partial(f.subs, x), potential_points+[a,b])))

def estimate_n(f,a,b,bias):
  x, N = symbols("x N")
  M = abs_sup(diff(f(x)),a,b)
  _N = float(solve(((b-a)**2)*M/(2*N) - bias, N)[0])
  return ceil(_N)+1

f = lambda x0: (x0-1)*(x0/2-3)
a, b, bias = 1, 4, 10**(-5)
x = symbols("x")

I1 = area(f,a,b,bias)
I2 = integrate(abs(f(x)), (x,a,b))

e = abs(I2-I1)

print(f"""
Pole między osią OX a funkcją f:
 - numerycznie: {I1}
 - symbolicznie: {I2.evalf()}
""")
print(f"Błąd całkowania: {e}")
print(f"Błąd jest {'' if e < bias else 'nie'}mniejszy niż {bias}")



Pole między osią OX a funkcją f:
 - numerycznie: 6.749995999998168
 - symbolicznie: 6.75000000000000

Błąd całkowania: 0.00000400000183198301
Błąd jest mniejszy niż 1e-05


#### Zadanie 2
a) Zaimplementuj w postaci funkcji algorytm obliczania pierwiastka kwadratowego z $x>0$ z wykorzystaniem algorytmu Herona. Funkcja powinna przyjmować jako argumenty liczby: $x$, punkt startowy $x_0$ oraz liczbę kroków (wyrazów ciągu do obliczenia).

b) Następnie, dodaj argument show_step (domyślnie ustawiony jako False), który będzie pozwalał wyświetlać kolejne kroki przybliżenia aż do zadanego.

c) Na bazie a) stwórz nową funkcję, która wykona odpowiednią liczbę kroków by przybliżenie miało podaną dokładność

In [ ]:
from functools import reduce
from itertools import count

def _root(x, x0, k, show_step=False):
  def x_next(x_k, step):
    _x = (1/2)*(x_k + x/x_k)
    if show_step:
      print(f"Krok {step}: {_x}")
    return _x
  return reduce(x_next, range(1, k+1), x0)

def root(x, bias=0.01):
  if x <= 0:
    raise ValueError("x has to be positive real number.")
  x_ = lambda k: _root(x,x,k)
  d = lambda x_k: (1/2)*(-x_k + x/(x_k))
  bias_criterion = lambda x_k: abs(d(x_k)) < bias
  return next(x_(k) for k in count(1) if bias_criterion(x_(k)))

print(f"Pierwiastek z 9 to: {_root(9, 1, 5, show_step=True)}")
print(f"Pierwiastek z 123456789 z dokładnością do 10**(-7): {root(123456789,bias=10**(-7))}")

Krok 1: 5.0
Krok 2: 3.4
Krok 3: 3.023529411764706
Krok 4: 3.00009155413138
Krok 5: 3.000000001396984
Pierwiastek z 9 to: 3.000000001396984
Pierwiastek z 123456789 z dokładnością do 10**(-7): 11111.111060555555


# NumPy

np.ndarray (N-dimensional array)

Najważniejsze atrybuty:
* shape
* ndim
* size
* dtype (int,float,bool,complex)
* nbytes


In [ ]:
tab=np.array([[1,2],[3,4],[4,1]])

In [ ]:
tab.nbytes

48

#### Zadanie 3

Stwórz dowolną tablicę liczb całkowitych ndarray z zagnieżdżonej listy. Sprawdź jej różne atrybuty. Spróbuj zamienić wszystkie liczby całkowite na zmiennoprzecinkowe.

In [ ]:
tab2=np.array(tab,dtype=float)

In [ ]:
tab2

array([[1., 2.],
       [3., 4.],
       [4., 1.]])

In [ ]:
tab3=np.array([-1,0,1])

In [ ]:
np.sqrt(tab3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([nan,  0.,  1.])

In [ ]:
tab4=tab3.astype(complex)
tab4
np.sqrt(tab4).imag

array([1., 0., 0.])

### Konstruktory:
* np.array - tworzy z różnych tablicopodobnych typów
* np.zeros - same zera
* np.ones - same jedynki
* np.eye - macierz identycznościowa
* np.diag - macierz z elementami na przekątnej

* **!** np.linspace(start,koniec (domknięty),liczba elementów)
* **!** np.arange(start,koniec (otwarty),krok)
* np.meshgrid - tworzy siatkę punktów z pojedynczych wektorów) - zwraca tablice poszczególnych współrzędnych

from scipy.linalg import block_diag

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.meshgrid([1,2,3],['a','b','c'])

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]), array([['a', 'a', 'a'],
        ['b', 'b', 'b'],
        ['c', 'c', 'c']], dtype='<U1')]

#### Zadanie 4
Skonstruuj macierz:
$$
Mat1=\begin{bmatrix}
1 &1 &0&0&0&0&0\\
1&1&0&0&0&0&0\\
0&0&0&0&0&0&0 \\
0&0&0&0&0&0&0 \\
0&0&0&0&3&0&0 \\
0&0&0&0&0&2&4 \\
0&0&0&0&0&4&2 \\
\end{bmatrix}
$$

In [4]:
import numpy as np
from scipy.linalg import block_diag
Mat1=block_diag(np.ones((2,2)),np.zeros((2,2)),3,(4*np.ones((2,2))-2*np.eye(2)))
Mat1[:2,:2]

array([[1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0., 2., 4.],
       [0., 0., 0., 0., 0., 4., 2.]])

In [ ]:
Mat1[0,0]=3

In [ ]:
Mat1

array([[3., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0., 2., 4.],
       [0., 0., 0., 0., 0., 4., 2.]])

In [ ]:
Mat1[:,::-1]

array([[0., 0., 0., 0., 0., 1., 3.],
       [0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0.],
       [4., 2., 0., 0., 0., 0., 0.],
       [2., 4., 0., 0., 0., 0., 0.]])

#### Zadanie 5
W macierzy Mat1 zamień miejscami lewy górny narożnik 4X4 z prawym dolnym 3x3 (nazwij wynik Mat2)

#### Zadanie 6
Stwórz macierz Mat3, która będzie zawierała tylko elementy z Mat2 o obu parzystych współrzędnych.

In [ ]:
Mat1[:4,:4]

array([[3., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
Mat1[-3:,-3:]

array([[3., 0., 0.],
       [0., 2., 4.],
       [0., 4., 2.]])

In [ ]:
Mat2=block_diag(Mat1[-3:,-3:],Mat1[:4,:4])

In [ ]:
Mat3=Mat2[1::2,1::2]

### Zadanie 7
Utwórz tablicę

$$
\begin{bmatrix}
1&2&3&4\\
5&6&7&8 \\
9&10&11&12\\
13&14&15&16
\end{bmatrix}
$$

In [8]:
import numpy as np

A = np.arange(1,17).reshape(4,4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Inne przydatne funkcje:

* łączenie macierzy ```np.concatenate((tab1,tab2),argumenty)```
* rozdzielanie macierzy ```np.array_split(tab1, \<liczba czesci\>)```
* wybieranie indeksów spełniających logiczny warunek: ```np.where(tab1>0)```
* sortowanie ```np.sort(tab1)```

In [16]:
import numpy as np 

M = np.fromfunction(lambda i,j,k: 100+60*i+10*j+300*k, (5,6,3))
M

array([[[100., 400., 700.],
        [110., 410., 710.],
        [120., 420., 720.],
        [130., 430., 730.],
        [140., 440., 740.],
        [150., 450., 750.]],

       [[160., 460., 760.],
        [170., 470., 770.],
        [180., 480., 780.],
        [190., 490., 790.],
        [200., 500., 800.],
        [210., 510., 810.]],

       [[220., 520., 820.],
        [230., 530., 830.],
        [240., 540., 840.],
        [250., 550., 850.],
        [260., 560., 860.],
        [270., 570., 870.]],

       [[280., 580., 880.],
        [290., 590., 890.],
        [300., 600., 900.],
        [310., 610., 910.],
        [320., 620., 920.],
        [330., 630., 930.]],

       [[340., 640., 940.],
        [350., 650., 950.],
        [360., 660., 960.],
        [370., 670., 970.],
        [380., 680., 980.],
        [390., 690., 990.]]])

In [29]:
import numpy as np 

A = np.array([[1],[2]])
B = np.array([[3,4]])

C = 3*np.ones((2,2))
D = 2*np.ones((2,2))

E = np.random.random(100) 

F = np.arange(1,17).reshape(4,4)
x = np.array([1,2,3,4])
y = np.array([0,4,1,6])



(array([1, 3]),)

In [37]:
import numpy as np 
from numpy.linalg import inv, eig


A = np.array([[2,3],[0,2]])
B = np.array([[2,5],[3,8]])

C = B @ A @ inv(B)
eig(C)[0]

array([2.+3.41915903e-07j, 2.-3.41915903e-07j])